#===============================
#
# Config File :)
# 
#===============================
##

database:
  DB_HOST: #database hostname
  DB_NAME: #database name
  DB_PASS: #database password
  DB_PORT: #port number  (put the port number inside quotes eg: '5432')
  DB_USER: #database username

app:
  SECRET_KEY: #Secret key here